---
- name: Perform setup
  ansible.builtin.include_tasks: setup.yml

- name: Ensure "files" directory exists
  file:
    path: "{{ role_path }}/files"
    state: directory
    mode: 0700
  delegate_to: localhost

- name: Remove old ssh private keys
  file:
    path: "{{ role_path }}/files/{{ network_shortname }}-{{ inventory_hostname }}"
    state: absent
  delegate_to: localhost

- name: Remove old ssh public keys
  file:
    path: "{{ role_path }}/files/{{ network_shortname }}-{{ inventory_hostname }}.pub"
    state: absent
  delegate_to: localhost

- name: Generate new ssh keys
  shell: ssh-keygen -t ed25519 -f "{{ role_path }}/files/{{ network_shortname }}-{{ inventory_hostname }}" -q -N ""
  delegate_to: localhost

- name: Copy private keys to hosts
  copy:
    src: "{{ role_path }}/files/{{ network_shortname }}-{{ inventory_hostname }}"
    dest: "/home/tf2server/.ssh/sbpp_key_{{ network_shortname }}"
    owner: tf2server
    group: tf2server
    mode: 0600
