---
- name: Perform setup
  ansible.builtin.include_tasks: setup.yml

- name: Ensure "files" directory exists
  file:
    path: "{{ role_path }}/files"
    state: directory
    mode: 0600
  delegate_to: localhost

- name: Remove old ssh private keys
  file: 
    path: "{{ role_path }}/files/{{ network_shortname }}-{{ inventory_hostname }}"
    state: absent
  delegate_to: localhost

- name: Remove old ssh public keys
  file: 
    path: "{{ role_path }}/files/{{ network_shortname }}-{{ inventory_hostname }}.pub"
    state: absent
  delegate_to: localhost

- name: Generate new ssh keys
  shell: ssh-keygen -b 2048 -t rsa -f "{{ role_path }}/files/{{ network_shortname }}-{{ inventory_hostname }}" -q -N ""
  delegate_to: localhost

- name: Copy private keys to hosts
  copy:
    src: "{{ role_path }}/files/{{ network_shortname }}-{{ inventory_hostname }}"
    dest: "/home/tf2server/.ssh/sbpp_key"
    owner: tf2server
    group: tf2server
    mode: 0600

- name: Ensure host ~/.config directory exists
  file:
    path: ~/.config
    state: directory
    mode: 0744

- name: Ensure host ~/.config/systemd directory exists
  file:
    path: ~/.config/systemd
    state: directory
    mode: 0744

- name: Ensure host ~/.config/systemd/user directory exists
  file:
    path: ~/.config/systemd/user
    state: directory
    mode: 0744

- name: Create ssh tunnel service
  template:
    src: sbpp_tunnel.service.j2
    dest: ~/.config/systemd/user/sbpp_tunnel.service
    mode: 0600

- name: Enable & start tunnel service
  ansible.builtin.systemd_service:
    name: sbpp_tunnel
    state: restarted
    daemon_reload: true
    enabled: true
    scope: user
