---
- name: Perform setup
  ansible.builtin.include_tasks: setup.yml

- name: Create build directory
  ansible.builtin.file:
    path: ~/build-relay/
    state: directory
    mode: 0755

- name: Copy build sources
  ansible.builtin.synchronize:
    src: "{{ role_path }}/files/"
    dest: ~/build-relay/
    archive: false
    recursive: true
    rsync_opts:
      - --exclude=target
      - --exclude=config.yml
      - --exclude=manifest.yml

- name: Prune space before building
  containers.podman.podman_prune:
    images: true
    containers: true

- name: Build rocket.rs binary
  containers.podman.podman_image:
    name: ansible-tf2network-relay-build
    image: rust:1.74-slim-bookworm
    state: started
    auto_remove: true
    volumes:
      - /home/tf2server/build-relay:/build
    command: /build/build.sh

- name: Wait for container to close
  wait_for:
    path: /home/tf2server/build-relay/.lock
    state: absent
    delay: 10
