---
- name: Delete old build data
  ansible.builtin.file:
    state: absent
    path: ~/build-relay/{{ instance.name }}

- name: Create build directory
  ansible.builtin.file:
    path: ~/build-relay/{{ instance.name }}
    state: directory
    mode: 0755

- name: Copy files
  ansible.posix.synchronize:
    src: "{{ role_path }}/files/"
    dest: ~/build-relay/{{ instance.name }}
    recursive: true

- name: Generate config.yml
  ansible.builtin.template:
    src: config.yml.j2
    dest: ~/build-relay/{{ instance.name }}/config.yml
    mode: 0755

- name: Prune space before building
  community.docker.docker_prune:
    images: true
    containers: true

- name: Build image
  community.docker.docker_image:
    name: "srcdsr-{{ instance.name }}"
    tag: "latest"
    source: build
    build:
      path: ~/build-relay/{{ instance.name }}
      pull: true
    state: present
    force_source: true
    force_tag: true
