---
- name: Perform setup
  ansible.builtin.include_tasks: setup.yml

- name: Generate admins
  include_tasks: gen_admins.yml
  loop: "{{ targets.instances }}"

- name: Move into container
  containers.podman.podman_container_copy:
    container: "srcds-{{ item.name }}"
    src: ~/build/{{ item.name }}/tf/addons/sourcemod/configs/admins_simple.ini
    dest: /home/steam/tf-dedicated/tf/addons/sourcemod/configs/admins_simple.ini
  loop: "{{ targets.instances }}"
  delegate_to: "{{ ansible_host }}"

- name: Tell servers to reload admins
  rcon:
    address: "{{ ansible_host }}"
    port: "{{ item.port }}"
    password: "{{ item.secrets.rcon_pass }}"
    command: 'sm_reloadadmins'
  loop: "{{ targets.instances }}"
  loop_control:
    index_var: loop0
  delegate_to: localhost
