---
- name: Load secrets
  ansible.builtin.include_tasks: secrets.yml

- name: Make admins_simple.ini
  ansible.builtin.template:
    src: admins_simple.ini.j2
    dest: ~/build/{{ item.name }}/tf/addons/sourcemod/configs/admins_simple.ini
    mode: 0755
  loop: "{{ instances_secrets }}"
  loop_control:
    index_var: loop0

- name: Move into container
  community.docker.docker_container_copy_into:
    container: "srcds-{{ item.name }}"
    path: ~/build/{{ item.name }}/tf/addons/sourcemod/configs/admins_simple.ini
    container_path: /home/steam/tf-dedicated/tf/addons/sourcemod/configs/admins_simple.ini
  loop: "{{ instances_secrets }}"
  delegate_to: "{{ inventory_hostname }}"

- name: Tell servers to reload admins
  rcon:
    address: "{{ inventory_hostname }}"
    port: "{{ srcds_base_port + (loop0 * 10) }}"
    password: "{{ item.rcon_pass }}"
    command: 'sm_reloadadmins'
  loop: "{{ instances_secrets }}"
  loop_control:
    index_var: loop0
  delegate_to: localhost
