---
- name: Perform setup
  ansible.builtin.include_tasks: setup.yml

- name: Prune space before updating
  community.docker.docker_prune:
    images: true
    containers: true

- name: Run updater container
  community.docker.docker_container:
    name: "srcds-update-base"
    image: "jackavery/base-tf2server:latest"
    state: started
    volumes:
      - /home/tf2server/.lock:/home/steam/.base.lock
    command: "bash /home/steam/update.sh"

- name: Wait for update to finish
  wait_for:
    path: /home/tf2server/.base.lock
    state: absent
    delay: 10

- name: Commit changes
  ansible.builtin.shell: docker commit srcds-update-base jackavery/base-tf2server:latest

- name: Remove updater container
  community.docker.docker_container:
    name: "srcds-update-base"
    state: absent

- name: Update instances
  include_tasks: update.yml
  loop: "{{ targets.instances }}"

- name: Prune space after updating
  community.docker.docker_prune:
    images: true
    containers: true

- name: Redeploy
  ansible.builtin.include_role:
    name: deploy
