---
- name: Run updater container
  community.docker.docker_container:
    name: "srcds-update-{{ item.name }}"
    image: "srcds-{{ item.name }}:latest"
    state: started
    volumes:
      - /home/steam/.lock:/home/tf2server/.{{ item.name }}.lock
    command: "bash /home/steam/update.sh"

- name: Wait for update to finish
  wait_for:
    path: /home/tf2server/.{{ item.name }}.lock
    state: absent
    delay: 10

- name: Commit changes
  ansible.builtin.shell: docker commit srcds-update-{{ item.name }} srcds-{{ item.name }}:latest

- name: Remove updater container
  community.docker.docker_container:
    name: "srcds-update-{{ item.name }}"
    state: absent
