---
- name: Perform setup
  ansible.builtin.include_tasks: setup.yml

- name: Create build directory
  ansible.builtin.file:
    path: ~/sbpp
    state: directory
    mode: 0755

- name: Create network directory
  ansible.builtin.file:
    path: ~/sbpp/{{ network_shortname }}
    state: directory
    mode: 0755

- name: Transfer podman-compose.yml
  ansible.builtin.template:
    src: podman-compose.yml.j2
    dest: ~/sbpp/{{ network_shortname }}/podman-compose.yml
    mode: 0755

- name: podman compose down
  shell: podman compose -f ~/sbpp/{{ network_shortname }}/podman-compose.yml down

- name: podman compose up
  shell: podman compose -f ~/sbpp/{{ network_shortname }}/podman-compose.yml up -d
