---
- name: Perform setup
  ansible.builtin.include_tasks: setup.yml

- name: Create build directory
  ansible.builtin.file:
    path: ~/sbpp
    state: directory
    mode: 0755

- name: Create network directory
  ansible.builtin.file:
    path: ~/sbpp/{{ network_shortname }}
    state: directory
    mode: 0755

- name: Create Podman network
  containers.podman.podman_network:
    name: net-{{ network_shortname }}
    state: quadlet
    quadlet_options:
      - |
        [Install]
        WantedBy=ansible-tf2network_{{ network_shortname }}-metrics.service multi-user.target default.target

- name: Create SourceBans volume
  containers.podman.podman_volume:
    state: quadlet
    name: sourcebans-{{ network_shortname }}
    quadlet_options:
      - |
        [Install]
        WantedBy=ansible-tf2network_{{ network_shortname }}-metrics.service multi-user.target default.target

- name: Create MariaDB volume
  containers.podman.podman_volume:
    state: quadlet
    name: mariadb-{{ network_shortname }}
    quadlet_options:
      - |
        [Install]
        WantedBy=ansible-tf2network_{{ network_shortname }}-metrics.service multi-user.target default.target

- name: Template kube.j2
  ansible.builtin.template:
    src: "kube.yaml.j2"
    dest: "~/sbpp/{{ network_shortname }}/kube.yaml"
    mode: 0700

- name: Template quadlet.j2
  ansible.builtin.template:
    src: "quadlet.kube.j2"
    dest: "~/.config/containers/systemd/ansible-tf2network_{{ network_shortname }}-metrics.kube"
    mode: 0744

- name: systemd user daemon reload
  ansible.builtin.systemd_service:
    scope: user
    daemon_reload: true

