srcds_region: 1

instances:
  - name: "boxfort"
    hostname: "Boxes For Foxes | The Box Fort"
    maxplayers: 24
    mapcycle: "hangout"
    ruleset: "hangout"
    timelimit: 60
    stv_name: "/call to report players"

  - name: "ri"
    hostname: "Boxes For Foxes | rINSTAGIB"
    maxplayers: 12
    mapcycle: "rinstagib"
    ruleset: "rinstagib"
    timelimit: 20
    stv_name: "/call to report players"
