srcds_region: 1

instances:
  - name: "ri1"
    hostname: "rINSTAGIB | NA West"
    maxplayers: 12
    mapcycle: "rinstagib"
    ruleset: "rinstagib"
    timelimit: 20
    winlimit: 0
    maxrounds: 0
    stv_enabled: true
    tags:
      - instagib
      - rinstagib
      - ras
    motd: |
      -- RULES. --

      DO NOT BE A BIGOT.
      DO NOT BE TOXIC.
      DO NOT ABUSE EXPLOITS OR CHEAT.
      DO NOT THINK YOU CAN SKIRT AROUND THE RULES.
      YOU WILL BE PUNISHED.

      YOU MAY JOIN OUR DISCORD: https://discord.gg/V5Z29SXtsY

      -- WELCOME TO RAS INSTAGIB. --

      YOUR ROCKET LAUNCHER ONLY DEALS DAMAGE ON DIRECT HITS.
      YOUR ROCKET HITS WILL ALWAYS ONE-HIT KILL.

      YOUR SECONDARY IS REPLACED WITH A RAILGUN.
      MOMENTUM IS KEY. DEAL MORE DAMAGE THE FASTER YOU MOVE.

      YOUR MELEE HITS WILL ALWAYS ONE-HIT KILL.

      YOUR BUNNYHOPPING IS AUTOMATIC.
      YOUR AIR CONTROL IS STRONGER.
      YOUR AMMUNITION IS INFINITE.
