---
- name: Generate restart cronjob and install
  hosts: tf2
  tasks:
    - name: Add servers to cron
      set_fact:
        cron: |
          docker restart {% for item in instances %}
          srcds-{{ item.name }} {% endfor %}
    
    - name: Install cronjob (6AM UTC)
      ansible.builtin.cron:
        name: "srcds-restart"
        weekday: "*"
        minute: "0"
        hour: "6"
        job: "{{ cron }}"
      when: ansible_distribution == 'Ubuntu'
